### ISSUE TITLE
datafeeder should use a different database by default

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/docker#100]
Currently, the datafeeder app is configured to create schemas in the georchestra database.
As a result, uploading data as `testadmin` results in a `psc` schema being created among other application schemas - this is highly dangerous ...

```
georchestra=# \dn+
                                  List of schemas
     Name      |    Owner    |     Access privileges      |      Description       
---------------+-------------+----------------------------+------------------------
 atlas         | georchestra |                            | 
 console       | georchestra |                            | 
 datafeeder    | georchestra |                            | 
 extractorapp  | georchestra |                            | 
 geofence      | georchestra |                            | 
 geonetwork    | geonetwork  |                            | 
 mapfishapp    | georchestra |                            | 
 mapstore      | georchestra | georchestra=UC/georchestra | 
 ogcstatistics | georchestra |                            | 
 psc           | georchestra |                            | 
 public        | georchestra | georchestra=UC/georchestra+| standard public schema
               |             | =UC/georchestra            | 
(11 rows)
```

Instead, a dedicated database should be used

**Comment by groldan** [comment]
I assumed that'd be a matter of configuration and preference on a real deployment, but I see the inconvenience of finding out after the fact.
So I guess we should just set up a separate database on the same postgres docker container, and update the default `datafeeder.properties` accordingly?

Do you want me to take care of it?

**Comment by jeanpommier** [comment]
Personnally, I tend to use a separate container, to keep things separate: 

- one database container for the applications' database
- one database container for the data and geodata

I feel it's more secure, and more reliable, say, in case the geodata DB gets overwhelmed at some point, it doesn't affect the apps' DB, so the apps continue working.

Also, for scheduling and storage, you might not have the same needs for each of them.

**Comment by fvanderbiest** [comment]
> Personnally, I tend to use a separate container

Agreed.
If someone has time to make the change here, that would be awesome.

**Comment by groldan** [comment]
@fvanderbiest, @jeanpommier, please check
- https://github.com/georchestra/datadir/pull/217
- https://github.com/georchestra/docker/pull/112
