### ISSUE TITLE
cannot build ldap

### ISSUE THREAD

**Issue by MaxiReglisse** [georchestra/docker#12]
in order to rebuild the ldap image, i modified the new docker-compose.yml file with the following line (in the "docker" directory):

    build: ../georchestra/ldap

i did not change SLAPD_PASSWORD (SLAPD_PASSWORD=secret), of course, but the building process fails because it needs the ldap admin password. i do not know why...

    debconf: unable to initialize frontend: Dialog
    debconf: (TERM is not set, so the dialog frontend is not usable.)
    debconf: falling back to frontend: Readline
    Configuring slapd
    Please enter the password for the admin entry in your LDAP directory.
    Administrator password: ...

then you must break the process with ctrl-Z.
I tried to work around the problem with two environment variables:

    ENV DEBIAN_FRONTEND noninterative
    ENV TERM linux

but then installing ldap-utils fails miserably... 

did you encounter this problem?

Thanks in advance.

Ernest.

**Comment by MaxiReglisse** [comment]
Problem solved by adding DEBIAN_FRONTEND=noninteractive just before apt-get install -y...

    FROM dinkel/openldap
    RUN apt-get update && \
        DEBIAN_FRONTEND=noninteractive apt-get install -y ldap-utils procps && \
        rm -rf /var/lib/apt/lists/*

**Comment by MaxiReglisse** [comment]
erratum: it works only if you rebuild the dinkel/openldap image locally... 
from [dinkel/docker-openldap](https://github.com/dinkel/docker-openldap)

**Comment by fvanderbiest** [comment]
Fixed now
