### ISSUE TITLE
mapstore/home returns an empty page

### ISSUE THREAD

**Issue by jmbourdaret** [georchestra/docker#123]
When running the docker composition of the *22.0* branch
https://georchestra-127-0-1-1.traefik.me/mapstore/#/home
returns an empty page, only the header is present. no errors in console or in the logs of the container.

https://georchestra-127-0-1-1.traefik.me/mapstore/ works fine.

If I replace the image `georchestra/mapstore:22.0.0-georchestra`
with `georchestra/mapstore:latest` in the docker composition, it works => I get the expected "_No maps available_"
If I replace the image `georchestra/mapstore:22.0.0-georchestra`
with `georchestra/mapstore:2021.02.xx` in the docker composition, it fails => empty page"

I believe that https://github.com/georchestra/mapstore2-georchestra/tree/2021.02.xx is considered the release branch of *mapstore* (geOr flavor), on which the tag `22.0.0-georchestra` was put recently.  And `master` is the development branch, from which `latest` is built.

**Comment by fvanderbiest** [comment]
@landryb can you help untangle this mess ? Where is mapstore/home supposed to be available ?

**Comment by landryb** [comment]
i .. dunno. Iirc https://github.com/georchestra/mapstore2-georchestra/pull/445 adds it to master.

According to https://github.com/georchestra/mapstore2-georchestra/commits/2021.02.xx that PR wasnt backported there, and my impression was that it was supposed to be ? @catmorales @offtherailz ?

**Comment by catmorales** [comment]
Hello! For me /mapstore/#/home is not available on 21.02.xx branch, just on master for now.
I have to see this with Tobia.

**Comment by jmbourdaret** [comment]
> Hello! For me /mapstore/#/home is not available on 21.02.xx branch, just on master for now.

Thanks for your quick reply !

Or maybe we should disable the `mapstore/#/home` feature for geOr 22.0.0 ?
geor tags on `2021.02.xx` :  https://github.com/georchestra/mapstore2-georchestra/tags

**Comment by pmauduit** [comment]
> Or maybe we should disable the `mapstore/#/home` feature for geOr 22.0.0 ?

:+1:

**Comment by landryb** [comment]
tss.. dont be so quick ;) https://github.com/georchestra/mapstore2-georchestra/pull/501 -> with that, latest builds from `2021.02.xx` should have the homepage.

**Comment by catmorales** [comment]
Yes wait a little . It will  probably  be backported soon.
From what I see it was done yesterday :. Thanks @landryb

**Comment by ChiranthTL** [comment]
Hey Guys, any update on this ? has been this resolved now ? 
any information would be helpful !

**Comment by landryb** [comment]
from what i can remember, it was fixed by georchestra/mapstore2-georchestra#501 but i have no idea about the docker setup/repo/etc.

**Comment by jeanmi151** [comment]
working now for me, closing
