### ISSUE TITLE
datafeeder-frontend - weird image tag on 22.0 branch

### ISSUE THREAD

**Issue by pmauduit** [georchestra/docker#125]
https://github.com/georchestra/docker/blob/22.0/docker-compose.yml#L202

This is mainly due to the fact that the docker images are generated from georchestra/geonetwork-ui, which does not have a "22.0.x-ish" branch, as opposed to GN and the other repositories (CAS6 ...).

debian packages should be fine in regards to the generated versions, because we have a dedicated module in georchestra/georchestra for the df-frontend. I think we should have a branch in georchestra/geonetwork-ui dedicated to build the 22.0.x serie, even if the branch won't derive much from the `georchestra-datafeeder` one.

Other option would be to make sure the docker composition is making use of the last 22.x tag available on docker hub.

**Comment by fvanderbiest** [comment]
> I think we should have a branch in georchestra/geonetwork-ui dedicated to build the 22.0.x serie

:+1:

**Comment by jahow** [comment]
Closed by #170 and #171
