### ISSUE TITLE
WARNING: JDBC URL invalid port number: ${pgsqlPort}

### ISSUE THREAD

**Issue by MkLHX** [georchestra/docker#126]
Hello, 
I'm trying to test the Georchestra stack using docker from branch 20.1 and 22.0
Analytics and Console containers failed to connect to database.

Each time the logs says:
```
 url:             jdbc:postgresql://${pgsqlHost}:${pgsqlPort}/${pgsqlDatabase}
 username:        ${pgsqlUser}
 driverClassName: org.postgresql.Driver
Aug 24, 2022 8:40:53 AM org.postgresql.Driver parseURL
WARNING: JDBC URL invalid port number: ${pgsqlPort}
------------------------> DB not ready - waiting <---------------------------
```
i start the stack using:
```
docker compose -f docker-compose.yml -f docker-compose.override.yml up -d
```

I don't know how to do more research about troubleshooting because i'm not a spring/java developer.

**Comment by fvanderbiest** [comment]
Hey, thanks for the report ! 
I just checked on a fresh 22.0 composition - it works.
Did you clone recursively the repository ? ie do you have files in the config subfolder ?

**Comment by MkLHX** [comment]
Hi, Thank you for the reply.
I cloned the repo and run docker-compose up the first time.
I retry from scratch following each readme steps. And now the stack is working.
Now I'm facing an error about credentials.
I'm going to check the georchestra docs.

They're is a way to launch georchestra without git clone and submodule update?

**Comment by fvanderbiest** [comment]
> They're is a way to launch georchestra without git clone and submodule update?

I checked github's ZIP feature but the submodule isn't provided.

As a result, you need 2 downloads to get eg stable release 22.0:
 * https://github.com/georchestra/docker/archive/refs/heads/22.0.zip
 * https://github.com/georchestra/datadir/archive/refs/heads/docker-22.0.zip to populate the config subfolder
