### ISSUE TITLE
CAS - image tag inhomogeneity

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/docker#129]
On `22.0`, all webapps use the `22.0.x` tag:
```
  proxy:
    image: georchestra/security-proxy:22.0.x
```

Except CAS:
```
  cas:
    image: georchestra/cas:22.0.0-georchestra
```

**Comment by pmauduit** [comment]
not except cas, mapstore2 does not follow the convention either

**Comment by pmauduit** [comment]
main reason is when you set a tag on a separate repository and the build is no longer managed by the georchestra/georchestra repository, then it does not make sense to tag with a version number relative to geOrchestra, but not to the upstream project (e.g. 22.0.4 does not mean anything when dealing with CAS).

**Comment by fvanderbiest** [comment]
You're 100% right.
