### ISSUE TITLE
traefik - upgrade to 2.8

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/docker#130]
We currently ship 2.4 

https://hub.docker.com/_/traefik

**Comment by edevosc2c** [comment]
Upgraded by @fvanderbiest here: https://github.com/georchestra/docker/commit/1e37bbb4a295445d37f79d7808c94f12c30bbac7#diff-2286cdeca85adb587a9640aa34352ba7c2fb6e49c0129dab05892ff67d0d4c58R20
