### ISSUE TITLE
override - remove the override ?

### ISSUE THREAD

**Issue by pmauduit** [georchestra/docker#132]
We could merge the override into the docker-compose.yaml, so that we leave people the possibility to create their own override file for development purposes.

We discussed with @arnaud-morvan, and we could not see the intent behind the current override, as it prevents the users to have their own customized ones for e.g. development customizations (like JDWP on java containers, and so on ...).

**Comment by fvanderbiest** [comment]
It was meant to keep things separated between core georchestra stuff and implementation specific things (eg traefik)
But +1 if you want to merge both things.

**Comment by jeanmi151** [comment]
This can be done with `docker compose -f new-override-filename` or by renaming the files.
For development purpose I guess people have the ability to customize the deployment as they wish.
Closing.
