### ISSUE TITLE
remove extractorapp from header menu

### ISSUE THREAD

**Issue by jeanpommier** [georchestra/docker#135]
Extractorapp was removed in commit 48934c, but is still shown in the admin menu from the header

![image](https://user-images.githubusercontent.com/4491521/191746842-05d5da00-9a5d-4532-b0d1-5e869635e840.png)

**Comment by fvanderbiest** [comment]
Well it was removed from this repo but not from the main repo.
See https://github.com/georchestra/georchestra/issues/3847

**Comment by jeanpommier** [comment]
And, more important, not from the header 

https://github.com/georchestra/georchestra/blob/master/header/src/main/webapp/WEB-INF/jsp/index.jsp#L365-L375

Which shows a link that is not resolvable anymore

**Comment by jeanpommier** [comment]
Should we also remove it from the database config ? https://github.com/georchestra/georchestra/tree/master/postgresql still contains some extractorapp files

**Comment by fvanderbiest** [comment]
> Should we also remove it from the database config

Yes, at the same time we remove it from master (ideally for 23.0), but GDPR code relies on it... (@emmdurin working on it)

**Comment by fvanderbiest** [comment]
Should be tackled by https://github.com/georchestra/georchestra/pull/3919
Closing here.
