### ISSUE TITLE
datafeeder not waiting for DB to be ready ?

### ISSUE THREAD

**Issue by jeanpommier** [georchestra/docker#136]
When first starting the composition, it looks like some times at least, the datafeeder starts before the backing DB, which results in daatafeeder failure (`Unable to open JDBC Connection for DDL execution`)

Experienced with version 22.0

**Comment by pmauduit** [comment]
I have another issue, but which looks like related to your one:

```
datafeeder_1                         | 2022-10-11 12:39:30.927  INFO 1 --- [         task-4] o.g.d.b.service.PublishingBatchService   : Publish 0266ff95-40ef-4e71-a21b-c8585a74ec46: importing datasets to target database
postgis_1                            | 2022-10-11 12:39:30.960 UTC [34] ERROR:  function postgis_lib_version() does not exist at character 8
postgis_1                            | 2022-10-11 12:39:30.960 UTC [34] HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
postgis_1                            | 2022-10-11 12:39:30.960 UTC [34] STATEMENT:  select PostGIS_Lib_Version()
```

I indeed had to install the extension by hand in order to be able to publish a dataset via the DF.

**Comment by ChiranthTL** [comment]
In version 22.0 am getting DB not ready error message when docker-compose up. 
any idea what it is causing the error ?
Please help !

**Comment by pmauduit** [comment]
> any idea what it is causing the error ?

Anything from the `database` docker container's logs ? (`docker-compose logs database`)

**Comment by ChiranthTL** [comment]
here you go..

![Screenshot from 2023-01-06 09-57-42](https://user-images.githubusercontent.com/101318997/210978371-d1e4c357-f96c-42a8-936d-c613f4d35361.png)
![Screenshot from 2023-01-06 09-57-24](https://user-images.githubusercontent.com/101318997/210978375-407cb695-3dd2-4056-94bc-fea12e54055c.png)

**Comment by edevosc2c** [comment]
We could add a "depend" on database for the service datafeeder: https://github.com/georchestra/docker/blob/master/docker-compose.yml#L176

**Comment by jeanpommier** [comment]
@edevosc2c  if you're talking about the inital topic of this issue, it won't be enough AFAIK. On the first run (DB not initialized yet) the db container will soon be "ready", i.e. running, but the DB itself won't be available at once, first init takes a few seconds.

**Comment by edevosc2c** [comment]
If we use this new functionality in the newer docker compose version, this will work:
```
depends_on:
   database:
      condition: service_healthy
```

It does it in fact wait for the database:
![image](https://user-images.githubusercontent.com/121870973/228186290-10f0f0b5-d384-4a8c-b8f7-d02204e9f0bc.png)

The only downside is that we will require everyone to use the new built-in docker compose and the old docker-compose won't work anymore.

Found in https://stackoverflow.com/a/74449969

**Comment by jeanpommier** [comment]
That's an interesting information. But quite a big drawback.

It depends on how much irrevocable this is. If this is just a matter of commenting one line to be able to get back to supporting the old docker-compose, I'd say we can go with it at the condition that it is properly documented in this repo (and in the docker-compose.yml).

After all, this is providing a better user experience, but the current config can still work, it's just not straightforward (you have actually to docker-compose up then docker-compose restart datafeeder I believe)

**Comment by edevosc2c** [comment]
I don't think we should support the old docker-compose V1, according to Docker it is set to be removed:
> From the end of June 2023 Compose V1 won’t be supported anymore and will be removed from all Docker Desktop versions.

Taken from https://docs.docker.com/compose/

Nowadays, this plugin is included by default in Docker, so there is no point in using the old docker-compose V1.

**Comment by jeanpommier** [comment]
There will still be some enivironments using the old v1 for some time. And documenting a work-around is not really "supporting" a version. Just making sure we don't drop users simply by being too "cutting edge"

**Comment by fvanderbiest** [comment]
I'd say : let's go forward for the 23.0 release ?
I'm +1 on using "docker compose" rather than "docker-compose" for this release.
This repository was never meant to be used in production, but rather used as a starting point.

**Comment by edevosc2c** [comment]
I've created a PR for fixing this issue: https://github.com/georchestra/docker/pull/173
And a note for those that are running old versions of Compose plugin: https://github.com/georchestra/docker/pull/173/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R36

Even though you can use the Compose plugin V2 for old machines as the new plugin is written in Golang and will work out of the box without any "pip install" or "apt install": https://docs.docker.com/compose/install/other/
