### ISSUE TITLE
Geonetwork Downloads and Links

### ISSUE THREAD

**Issue by naveenshaw** [georchestra/docker#147]
Hello everyone,

Am using georchestra docker 22.0 on ubuntu. earlier when a shapefile was uploaded on the metadata record on the download and links. 
in the links the WMS and WFS which used to work. now it is not working and even the option add to map wil

l not work even though my projection is 4326 it says it is in a different projection and fails.

and the WMS and WFS links has a same link and when clicked gives no service error. 

![Screenshot from 2023-01-11 18-14-14](https://user-images.githubusercontent.com/64439964/211809562-f9c07590-025d-4b0c-b72b-2547cbfaf508.png)
![Screenshot from 2023-01-11 18-16-20](https://user-images.githubusercontent.com/64439964/211809894-93802f82-54e3-4880-bd76-54dc88cce37a.png)

**Comment by fvanderbiest** [comment]
Maybe this helps: https://github.com/georchestra/georchestra/tree/master/migrations/22.0#link-to-external-viewer

Regards
