### ISSUE TITLE
Instructions to create and use your own TLS certificate for local development

### ISSUE THREAD

**Issue by severo** [georchestra/docker#15]
In https://github.com/georchestra/docker/tree/master/resources/ssl, certificates are provided to allow dockerized applications to use HTTPS without any problem.
But I understand it's a security problem for the developer, because if they trust the certificate, as the private key is published on the web, any website could use it, and your browser would trust it. See https://letsencrypt.org/docs/certificates-for-localhost/. (I understand that the attacker should also realize MITM on DNS lookup, but it's still possible, since most of the DNS traffic is not encrypted nowadays...)

For this reason, I understand that it would be safer for the developer to generate its own certificate, and to tell the dockerized applications to use it.

**Comment by fvanderbiest** [comment]
> I understand it's a security problem for the developer, because if they trust the certificate

Yes, they should trust the certificate for the current browsing session only.
Risks are low but I understand your point here.

If we could automate the self-signed certificate generation on first startup, that would solve the issue.

**Comment by RemiDesgrange** [comment]
You can use https://github.com/FiloSottile/mkcert

* `mkcert -install` -> will install the root certs on you're machine (do it once)
* `cd resources/ssl && mkcert georchestra.mydomain.org`
* eventually rename the generated cert and private key.

@severo can we close it ?
