### ISSUE TITLE
Shouldn't we have a branch for every georchestra version?

### ISSUE THREAD

**Issue by severo** [georchestra/docker#16]
This repository uses the datadir submodule, that manages `docker-18.06` and `docker-master` branches. The submodule here points to the `docker-master` branch.

I wonder if we shouldn't have:

- one set of docker images for every geOrchestra version, at least 18.06 and master for the moment, updated at every commit
- one branch for every geOrchestra version, at least 18.06 and master for the moment.
- one set of docker volumes for every geOrchestra version

What do you think?

**Comment by fvanderbiest** [comment]
Done, at last !
