### ISSUE TITLE
Datahub -  undefined volume georchestra_datadir

### ISSUE THREAD

**Issue by Gaetanbrl** [georchestra/docker#162]
Hi,

Datahub volume seems missing from datadir.

https://github.com/georchestra/docker/blob/2a6f6f6742a06028ddf09c3248668544541d6eeb/docker-compose.yml#L140

# Errors :

> service "datahub" refers to undefined volume georchestra_datadir: invalid compose project

# Commands to reproduce : 

```
  git clone --recurse-submodules https://github.com/georchestra/docker.git
  cd docker/
  docker compose up
```

**Comment by fvanderbiest** [comment]
Thanks for the report !

**Comment by Gaetanbrl** [comment]
just a question @fvanderbiest , how do you know the path of a specific volume ?

**Comment by fvanderbiest** [comment]
docker inspect myvolume | grep Mountpoint
