### ISSUE TITLE
Container issues (404, 503) even though followed README instructions exactly

### ISSUE THREAD

**Issue by diegoripley** [georchestra/docker#166]
I am getting some issues with the containers (404 and 503 errors) (see [1]). I followed the instructions exactly as on the README.md. How can I troubleshoot this issue? I am not a Java developer so I do not know where to start. Thank you in advance.

[1] https://www.youtube.com/watch?v=T6vgb5aATj0

![DeepinScreenshot_select-area_20230315115520](https://user-images.githubusercontent.com/6893641/225367046-40366ac5-a8ac-426f-a2d9-5c6da9d50778.png)
![DeepinScreenshot_select-area_20230315115532](https://user-images.githubusercontent.com/6893641/225367052-59e33ff0-0f21-44ed-aaf2-91f26686b6f1.png)
![DeepinScreenshot_select-area_20230315141943](https://user-images.githubusercontent.com/6893641/225405828-7a243536-c5a0-4f93-a9f3-cffc5377b183.png)
![DeepinScreenshot_20230315142119](https://user-images.githubusercontent.com/6893641/225406122-9e5a7727-85ae-48b3-ba9c-309d19cee106.png)

**Comment by Gaetanbrl** [comment]
@arnaud-morvan look like my code sprint IP (v6 ?) trouble  ?

**Comment by diegoripley** [comment]
Could this issue have something to do with the ldap container? I updated the issue with two new images.

**Comment by fvanderbiest** [comment]
Indeed your LDAP instance seems flacky.
What does `docker logs docker_ldap_0` provide ?

**Comment by diegoripley** [comment]
From what I see the logs don't provide anything useful. Is there a setting to change the logs to debug?
```
docker-ldap-1  | run-parts: executing /docker-entrypoint.d/00-init
docker-ldap-1  | Info: Container already configured, therefore ignoring SLAPD_xxx environment variables and preseed files
docker-ldap-1  | run-parts: executing /docker-entrypoint.d/01-populate
docker-ldap-1  | Starting slapd daemon in background...Started: OK
```

**Comment by fvanderbiest** [comment]
> From what I see the logs don't provide anything useful. Is there a setting to change the logs to debug?

Yes, see https://github.com/georchestra/docker/blob/da23e98b68ecd8b650b6f5045aa7e1754fb2c41b/docker-compose.yml#L43

**Comment by diegoripley** [comment]
It's not producing any more detailed logs. I changed it to `SLAPD_LOG_LEVEL=4` and deleted the ldap volume before restarting the Docker container.

**Comment by diegoripley** [comment]
It's odd. I tried it on my **work computer** and I am at least getting this, I am not getting that on my personal computer even though I type the exact same commands. I thought Docker was supposed to remove issues like this. 
![image001](https://user-images.githubusercontent.com/6893641/225670722-dbcc0c49-d6dd-4d5a-8e07-b852ee3992ae.png)

**Comment by diegoripley** [comment]
Tried on another one of my servers and I am getting the following.

![DeepinScreenshot_select-area_20230316190015](https://user-images.githubusercontent.com/6893641/225773954-2d6b2690-ad7e-4a46-9017-e5e255b98b05.png)

**Comment by fvanderbiest** [comment]
Just tested branch `22.0`, it works fine.
Did you pull images recently ? Or it has something to do with the LDAP dump.

**Comment by pmauduit** [comment]
> Tried on another one of my servers and I am getting the following.

slapd which would end up with a "core dump" is very unlikely. 2 things comes to my mind:

1. a too old docker version: I know that recent docker images (encountered with jetty-based ones) require a recent docker version or will refuse to boot (issues with memory allocations indeed). We had to launch some of our containers with the privileged mode to circumvent this.
2. Hardware issue with RAM banks ?

**Comment by pmauduit** [comment]
tested the `master` and `22.0` this morning, and I could not reproduce the issue. FYI I'm running the following version on my dev environment:

```
 % docker version                                                                                                                                             2023-03-17 10:54:27 pmauduit pts/1
Client: Docker Engine - Community
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Thu Feb  9 19:46:49 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Thu Feb  9 19:46:49 2023
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by diegoripley** [comment]
I was able to resolve the issue by installing Ubuntu and Docker on my other computer. There must be something wrong with my Arch Linux Docker configuration/installation.

**Comment by fvanderbiest** [comment]
Glad you finally made it !
