### ISSUE TITLE
mapping key "depends_on" already defined

### ISSUE THREAD

**Issue by MaxiReglisse** [georchestra/docker#177]
dear all, 

the latest version of docker causes an error when running ` docker compose up -d`.

    yaml: unmarshal errors:
      line 163: mapping key "depends_on" already defined at line 154

docker version: 23.0.2 (Mon Mar 27 16:16:39 2023)
we don't have this error with version 23.0.1...

deleting lines 163-167 from the docker-compose.yml file seems to solve the problem...

what do you think?

thanks in advance,

Ernest.

**Comment by jahow** [comment]
Can confirm, had this as well and fixed it in https://github.com/georchestra/docker/pull/172

**Comment by edevosc2c** [comment]
Just pushed a fix here so that it is fixed quickly for everyone: https://github.com/georchestra/docker/pull/178
