### ISSUE TITLE
Wich georchestra branch can i run with docker ?

### ISSUE THREAD

**Issue by Gaetanbrl** [georchestra/docker#209]
# Description / use case

> This is a question with a specific usecase.

I maintain an old georchestra version (e.g 15.12) and i need to develop a specific fix fastly.
So, it could be awesome to use Docker "Develop corner" doc to run georchestra 15.12 in a local VM.

# Question : 

Is it possible to do that ?
If not, with branch is compliant with docker or available in docker-hub ?

**Comment by pmauduit** [comment]
> Is it possible to do that ?

On former versions, it depends, the main requirement is to be able to get the docker images related to the version you want to run.
About the 15.12 version, I cannot find any docker images related to this specific one on docker-hub:
https://hub.docker.com/r/georchestra/security-proxy/tags?page=1&ordering=-last_updated

so you will probably have to generate them by yourself, taking back the 15.12 branch from the georchestra/georchestra git repository. It looks like the maven profile used to generate the docker image was already there though:
https://github.com/georchestra/georchestra/blob/15.12/security-proxy/pom.xml#L431-L494

**Comment by fvanderbiest** [comment]
Good luck with it...
