### ISSUE TITLE
Keeping in sync the config

### ISSUE THREAD

**Issue by RemiDesgrange** [georchestra/docker#22]
Keeping the submodule in sync is quite tricky. Here are options:

* using deployement in travis to update the reference in the submodule when a Pr is merge in https://github.com/georchestra/datadir/ 
* deleting the config submodule, and create a makefile (or script), that will clone the config repo, with the right branch, and launch the docker-compose.

WDYT ? @fvanderbiest  @pmauduit

**Comment by fvanderbiest** [comment]
I'd favor a periodic check (travis, other ?) that submodules in every branch point at the latest commit from the correct datadir branch (eg: docker-master for master, docker-19.04 for 19.04, docker-18.06 for 18.06)

**Comment by fvanderbiest** [comment]
See https://docs.travis-ci.com/user/cron-jobs/

**Comment by fvanderbiest** [comment]
More than just a check, the job should also be able to commit the change to this repo. 
No conflict expected.

**Comment by fvanderbiest** [comment]
See also https://dependabot.com/submodules/ https://github.com/marketplace/dependabot/ & https://github.com/apps/renovate https://github.com/renovatebot/renovate

**Comment by RemiDesgrange** [comment]
Ok I'm closing since dependabot does the job
