### ISSUE TITLE
Import tool error

### ISSUE THREAD

**Issue by superbully** [georchestra/docker#241]
Hi, i´t trying import a shape file from import tool and in the end setp, i have the next error: "Please fill mandatory fields" . Attach screen capture. Any idea about the error ?

![error](https://github.com/georchestra/docker/assets/10770450/74342fb0-419b-4c7c-a576-6e6dc19e2937)

**Comment by jeanmi151** [comment]
Hey,
 this field is connected to the local thesaurus of geonetwork, you need to change the configuration url of datafeeder in the file config/datafeeder/frontend-config.json
and apply it to your domain you are using

Ref to the config file online : https://github.com/georchestra/datadir/blob/9cfa0ae42053ee961eb5380bb22e34cebca807f9/datafeeder/frontend-config.json#L26

Note the default value is pointing to the default domain use by georchestra which is georchestra-127-0-1-1.traefik.me

**Comment by superbully** [comment]
Hi, thank you so much. It works perfectly !
Best regards !

**Comment by jeanmi151** [comment]
Your welcome 
best regards
