### ISSUE TITLE
Use sendmail to send email

### ISSUE THREAD

**Issue by superbully** [georchestra/docker#252]
Hi, i can´t get georchestra work with sendmail. I following the document "docker-compose.sendmail.yml" . In this document is
```
# To use it, you have to change the smtp config in config/default.properties to
# use `sendmail` host
```
In the file config/default.properties only are the variables 

smtpHost=${SMTPHOST}
smtpPort=${SMTPPORT}

If i set "smtpHost=sendmail", not work . I don´t know if it´s correct . Can someone tell me where it goes wrong?

Thank you so much !!

**Comment by edevosc2c** [comment]
only change the file here: https://github.com/georchestra/docker/blob/master/.envs-common

**Comment by superbully** [comment]
Hi, thank you very much for your reply. Now, if i change the file [https://github.com/georchestra/docker/blob/master/.envs-common](url) the mails not going to webmail, but not work. 
The container sendmail it´s up. I have changed in "docker-compose.sendmail.yml " the var " HOSTNAME" with my domain.
¿ Any ideas ?

Thank you very much.

**Comment by edevosc2c** [comment]
Look at the logs of the container that should send the email... Maybe your provider block the port 25 for outgoing connections and that's why you can't send emails?

Anyway the logs will tell everything what is going on.

**Comment by edevosc2c** [comment]
Closing due to lack of replies.
