### ISSUE TITLE
local env - Default install - 404 and header auth state

### ISSUE THREAD

**Issue by Gaetanbrl** [georchestra/docker#317]
> tag 24.0
> target env : local
> target system : debian 12

Hi,

According to README,  

I'd just follows basic steps :

- cd docker
- docker compose up -d
- Open https://georchestra-127-0-0-1.nip.io/ in your browser

But default header seems already logged and fully unusable. 

![image](https://github.com/user-attachments/assets/fc950589-4f78-482b-8d47-63e65c28e517)

Next, each georchestra link return 404 :

![image](https://github.com/user-attachments/assets/8008f70b-c9c9-47a1-b2f9-bb65ed32dba9)

**Comment by Gaetanbrl** [comment]
I guess this issue dupplicate https://github.com/georchestra/docker/issues/296

**Comment by Gaetanbrl** [comment]
Ok trouble come from folder name (renames on clone...) : 

https://github.com/georchestra/docker/issues/214

**Comment by jeanmi151** [comment]
also i can see that in the screenshot you use the old domain : https://georchestra-127-0-1-1.traefik.me/
now it is https://georchestra-127-0-0-1.nip.io/
