### ISSUE TITLE
LDAP : db_db_cache: db_open(mail) failed: Permission denied

### ISSUE THREAD

**Issue by MaxiReglisse** [georchestra/docker#6]
sometimes, rights are poorly positioned in /var/lib/docker/volumes/georchestra_ldap_data/_data/, and we encounter the following error : 

```
ldap_1                      | 5971c4ac bdb_db_cache: db_open(mail) failed: Permission denied (13)
ldap_1                      | 5971c4ac <= bdb_substring_candidates: (mail) index_param failed (13)
```
indeed, mail.bdb is root:root instead of syslog:systemd-bus-proxy : 

```
[root@service-info12 ~]# ls -l /var/lib/docker/volumes/georchestra_ldap_data/_data/
total 1032
-rw-r--r-- 1 syslog systemd-bus-proxy     2048 juil. 21 10:30 alock
-rw------- 1 syslog systemd-bus-proxy    16384 juil. 21 10:30 cn.bdb
-rw------- 1 syslog systemd-bus-proxy   589823 juil. 21 10:30 __db.001
-rw------- 1 syslog systemd-bus-proxy   147455 juil. 21 10:30 __db.002
-rw------- 1 syslog systemd-bus-proxy   286719 juil. 21 10:30 __db.003
-rw-r--r-- 1 syslog systemd-bus-proxy       96 juil. 21 10:30 DB_CONFIG
-rw------- 1 syslog systemd-bus-proxy     8192 juil. 21 10:30 dn2id.bdb
-rw------- 1 syslog systemd-bus-proxy    65536 juil. 21 10:30 id2entry.bdb
-rw------- 1 syslog systemd-bus-proxy 10485759 juil. 21 10:30 log.0000000001
-rw------- 1 root   root                  8192 juil. 21 10:30 mail.bdb
-rw------- 1 syslog systemd-bus-proxy     8192 juil. 21 10:30 member.bdb
-rw------- 1 syslog systemd-bus-proxy     8192 juil. 21 10:30 objectClass.bdb
-rw------- 1 syslog systemd-bus-proxy     8192 juil. 21 10:30 uid.bdb
```
it is easy to correct that with the chown command, but this is not satisfactory...

`chown -R syslog:systemd-bus-proxy /var/lib/docker/volumes/georchestra_ldap_data/_data`

What do you think ?

**Comment by pmauduit** [comment]
> What do you think ?

We encountered the same in production some weeks ago, for an unknown reason openldap achieves to create some files as root and does not change the owner to openldap:openldap, which can lead to the issue you encountered.

One fix could be to have a script just before launching slapd which ensures everything is owned by the correct user. (Also related to https://github.com/georchestra/georchestra/issues/1261)

**Comment by fvanderbiest** [comment]
Do you still encounter this kind of error @MaxiReglisse ? I think this was fixed in the mean time.

**Comment by MaxiReglisse** [comment]
no, it's OK now. Thanks.
