### ISSUE TITLE
DB not ready postgresql

### ISSUE THREAD

**Issue by chester59240** [georchestra/docker#62]
Good morning,

I tried to install Georchestra on docker (CentOS 8.2) but after docker-compose up I have an error:

```
console_1                   | ------------------------> DB not ready - waiting <---------------------------
console_1                   |  url:             jdbc:postgresql://database:5432/georchestra
console_1                   |  username:        georchestra
console_1                   |  driverClassName: org.postgresql.Driver

analytics_1                 | ------------------------> DB not ready - waiting <---------------------------
analytics_1                 |  url:             jdbc:postgresql://database:5432/georchestra
analytics_1                 |  username:        georchestra
analytics_1                 |  driverClassName: org.postgresql.Driver
```

That's my first time using docker.

Did someone already had the problem?

Thanks,

Paul

**Comment by chester59240** [comment]
If I log the compose-docker up > logs.txt

I have more java errors
```
[33mcas_1                       |^[[0m        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
^[[33mcas_1                       |^[[0m        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
^[[33mcas_1                       |^[[0m        at org.eclipse.jetty.server.Server.doStart(Server.java:371)
^[[33mcas_1                       |^[[0m        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
^[[33mcas_1                       |^[[0m        at org.eclipse.jetty.xml.XmlConfiguration.lambda$main$1(XmlConfiguration.java:1924)
^[[33mcas_1                       |^[[0m        at java.security.AccessController.doPrivileged(Native Method)
^[[33mcas_1                       |^[[0m        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1873)
^[[33mcas_1                       |^[[0m        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
^[[33mcas_1                       |^[[0m        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
^[[33mcas_1                       |^[[0m        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
^[[33mcas_1                       |^[[0m        at java.lang.reflect.Method.invoke(Method.java:498)
^[[33mcas_1                       |^[[0m        at org.eclipse.jetty.start.Main.invokeMain(Main.java:218)
^[[33mcas_1                       |^[[0m        at org.eclipse.jetty.start.Main.start(Main.java:491)
^[[33mcas_1                       |^[[0m        at org.eclipse.jetty.start.Main.main(Main.java:77)
```

**Comment by RemiDesgrange** [comment]
Hi, what's the status of the db (`docker-compose ps` and seeing if the "database" container is up and running).

Couple of tricks for docker and bug report:

* put your code in bracket "`" in order to make it more readable
* you can `docker-compose up -d && docker-compose logs -f <the container, like "console">` this way you only have the logs you want.
* the Java error you get is not related to db (but it is very low in the servlet stack, so I cannot guarantee that 100%)

**Comment by chester59240** [comment]
Hi,

Thanks for your response!

All docker component are up and running.
I tried to check logs more precisely but there is nothing more. "Information: DB is ready for connection" 

I will try to install Georchestra with a full install even if it looks more complicated...

**Comment by RemiDesgrange** [comment]
You can still try to add a line 

```yaml
ports:
  - "5432:5432"
```

In the db container  def :

```yaml
services:
  database:
    image: georchestra/database:latest
    environment:
      - POSTGRES_USER=georchestra
      - POSTGRES_PASSWORD=georchestra
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
```

And then connecting : `psql -U georchestra -h localhost georchestra` to see if the db works.

**Comment by chester59240** [comment]
I added ports as you specified, unfortunately  it doesn't work.

I tried to deploy georchestra with ANSIBLE as well, I get many problems too...
There should be an available ISO or VM to instantly deploy Georchestra ='(

**Comment by fvanderbiest** [comment]
Hi Paul,
To help you, can you tell us which branch of https://github.com/georchestra/docker you're running ?

**Comment by chester59240** [comment]
Hi François,
We used the default branch "Master". Should we try the 20.0?

Thanks!

**Comment by fvanderbiest** [comment]
Branch 20.0 is more tested indeed, it's supposed to be stable ;-)

**Comment by chester59240** [comment]
The link is the same for master and 20.0!
"https://github.com/georchestra/docker.git"
How can you specify wich branch you want to clone?

**Comment by fvanderbiest** [comment]
See "Switching Branches" in https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell or the [latest commit](67eb4755036950a972c52431e9fa1390569274c9) I made in this repo.

**Comment by chester59240** [comment]
I switched on the 20.0 branch thanks 👍

After docker-compose up I have now an LDAP and DB not ready! ='(

analytics_1                 | ------------------------> DB not ready - waiting <---------------------------
analytics_1                 |  url:             jdbc:postgresql://database:5432/georchestra
analytics_1                 |  username:        georchestra
analytics_1                 |  driverClassName: org.postgresql.Driver
cas_1                       | -------------> LDAP Not Ready waiting... on ldap://ldap:389 with login : cn=admin,dc=georchestra,dc=org Searching entry with '(uid=*)' in ou=roles,dc=georchestra,dc=org (24/300) <---------------
console_1                   | ------------------------> DB not ready - waiting <---------------------------
console_1                   |  url:             jdbc:postgresql://database:5432/georchestra
console_1                   |  username:        georchestra
console_1                   |  driverClassName: org.postgresql.Driver

**Comment by RemiDesgrange** [comment]
What's your docker setup ?

**Comment by fvanderbiest** [comment]
Maybe you should `docker-compose down -v` to clean volumes before starting again your composition on the `20.0` branch.

**Comment by chester59240** [comment]
I tried to docker-compose down -v before lauching again. Same problem.
It's a simple docker install, I didn't change anything

[root@vsrv-docker docker]# docker info
Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 1
  Paused: 0
  Stopped: 2
 Images: 30
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.18.0-193.14.2.el8_2.x86_64
 Operating System: CentOS Linux 8 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 23.36GiB
 Name: vsrv-docker
 ID: ELT3:MHLM:RA45:HXEI:4HTG:KR6D:5VB5:666W:WESI:6WEL:Y7QQ:2BBE
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by fvanderbiest** [comment]
Works out of the box for me on 20.0, wiping everything before with `docker-compose down -v` and pulling fresh images with `docker-compose pull`.
```
Docker version 19.03.12, build 48a66213fe
docker-compose version 1.17.0, build ac53b73
Linux 4.15.0-109-generic #110-Ubuntu SMP Tue Jun 23 02:39:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
