### ISSUE TITLE
docker-compose.overrides depends on public images from the Camptocamp organization

### ISSUE THREAD

**Issue by pmauduit** [georchestra/docker#77]
https://github.com/georchestra/docker/blob/master/docker-compose.override.yml#L38-L61

Camptocamp is planning to migrate from docker-hub to github packages, so there is a possibility that the referenced images above become unavailable in the future.

**Comment by pmauduit** [comment]
It might be possible to reference the [git repository](https://github.com/camptocamp/docker_smtp/blob/master/webmail/Dockerfile) to build the images anyway:
https://docs.docker.com/compose/compose-file/#context

so that the registry is not even necessary anymore.

**Comment by fvanderbiest** [comment]
> It might be possible to reference the [git repository](https://github.com/camptocamp/docker_smtp/blob/master/webmail/Dockerfile) to build the images anyway:

Sounds like a neat idea !

**Comment by jeanpommier** [comment]
we could also replace the 3 email-related images by a basic sendmail container, that would allow to really send the emails.

That's what I'm using on production

**Comment by RemiDesgrange** [comment]
@jeanpommier this setup is not really meant for production. The 3 containers are here for testing purpose, and quite helpful to help debug mail setup.

**Comment by fvanderbiest** [comment]
> we could also replace the 3 email-related images by a basic sendmail container, that would allow to really send the emails.

Mayb this could be provided in an alternate docker-compose file ? Thanks !

**Comment by jeanmi151** [comment]
Closing, there is no real issue using camptocamp's images.
