### ISSUE TITLE
Upgrade traefik

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/docker#78]
georchestra.mydomain.org_1  | time="2020-12-15T09:38:23Z" level=warning msg="A new release has been found: 2.3.5. Please consider updating."

**Comment by RemiDesgrange** [comment]
The problem with the upgrade to v2 is that the whole config need to be rewrite :-/

**Comment by fvanderbiest** [comment]
Well, that should not be a burden, it's light: https://github.com/georchestra/docker/blob/master/resources/traefik.toml
